name: Publish to npm and Create Release

on:
    push:
        branches:
            - master

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GH_PAT }}

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: 'https://registry.npmjs.org/'

            - name: Install Dependencies
              run: npm install

            - name: Run Tests
              run: npm test

            - name: Build Package
              run: npm run build

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    create-tag-and-release:
        needs: publish-npm
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GH_PAT }}

            - name: Get Package Version
              id: get_version
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  echo "VERSION=$VERSION" >> $GITHUB_ENV
              shell: bash

            - name: Create and Push Tag
              run: |
                  git config user.name "GitHub Action"
                  git config user.email "action@github.com"
                  git tag -a v${{ env.VERSION }} -m "Release ${{ env.VERSION }}"
                  git push origin v${{ env.VERSION }}

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: v${{ env.VERSION }}
                  name: Release ${{ env.VERSION }}
                  files: dist/**
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
