name: Publish to npm and Create Release

on:
    push:
        branches:
            - master

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: 'https://registry.npmjs.org/'

            - name: Install Dependencies
              run: npm install

            - name: Run Tests
              run: npm test

            - name: Build Package
              run: npm run build

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    create-tag-and-release:
        needs: publish-npm
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Get Package Version
              id: get_version
              run: echo 'VERSION=$(node -p "require(\'./package.json\').version")' >> $GITHUB_ENV

            - name: Create Git Tag
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"
                  git tag v${{ env.VERSION }}
                  git push origin v${{ env.VERSION }}

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: dist/**
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
